name: heroes
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ^2.0.0-dev

dependencies:
  aqueduct:
    path: /Users/joeconway/Projects/aqueduct

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
